// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // CLI-only (migrate/generate). The session-mode pooler supports the
    // prepared statements/DDL that migrations need; the app itself uses
    // DATABASE_URL (transaction pooler) via a driver adapter at runtime.
    url: process.env["DIRECT_URL"],
  },
});
